# Generated by Django 6.0.5 on 2026-06-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('fecha_hora', models.DateTimeField()),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
