# Generated by Django 6.0.5 on 2026-05-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
