# Generated by Django 6.0.5 on 2026-05-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_testimonial_email_alter_testimonial_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
