# Generated by Django 6.0.5 on 2026-05-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0003_alter_testimonial_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
