# Generated by Django 6.0.5 on 2026-05-29 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0005_alter_product_options_product_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
    ]
