# Generated by Django 6.0.5 on 2026-05-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_table_options_alter_reservation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={},
        ),
        migrations.AddField(
            model_name='table',
            name='x_position',
            field=models.IntegerField(default=0, help_text='Posición X en el mapa (0-4)'),
        ),
        migrations.AddField(
            model_name='table',
            name='y_position',
            field=models.IntegerField(default=0, help_text='Posición Y en el mapa (0-3)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
